// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// Command spdxgen regenerates spdx_data.go from the official SPDX license list.
//
// Run via `go generate ./spdx`. It fetches the pinned SPDX license-list-data
// release (listVersion below) and emits a case-insensitive lower→canonical map
// for both license ids and exception ids. The id data is vendored as a Go data
// table, NOT a module dependency — the spdx package stays stdlib-only, honoring
// the grc-store-protocol zero-dependency charter (ADR-0035).
//
// To bump the SPDX list: change listVersion to a newer tag of
// github.com/spdx/license-list-data, re-run `go generate`, and ship a MINOR
// release (additive — see the STABILITY note in spdx.go).
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// Pinned SPDX license-list-data release. Both consumers move together on this.
const listVersion = "3.28.0"

const baseURL = "https://raw.githubusercontent.com/spdx/license-list-data/v" + listVersion + "/json/"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "spdxgen:", err)
		os.Exit(1)
	}
}

func run() error {
	licenses, err := fetchIDs(baseURL+"licenses.json", "licenses", "licenseId")
	if err != nil {
		return err
	}
	exceptions, err := fetchIDs(baseURL+"exceptions.json", "exceptions", "licenseExceptionId")
	if err != nil {
		return err
	}
	if len(licenses) == 0 || len(exceptions) == 0 {
		return fmt.Errorf("refusing to write empty data (licenses=%d exceptions=%d)", len(licenses), len(exceptions))
	}

	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	b.WriteString("// Code generated by spdxgen.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: SPDX license-list-data v%s.\n\n", listVersion)
	b.WriteString("package spdx\n\n")
	fmt.Fprintf(&b, "// SPDXListVersion is the SPDX license-list-data release the bundled id\n")
	fmt.Fprintf(&b, "// tables below were generated from.\nconst SPDXListVersion = %q\n\n", listVersion)
	writeMap(&b, "spdxLicenseIDs", licenses)
	b.WriteString("\n")
	writeMap(&b, "spdxExceptionIDs", exceptions)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	return os.WriteFile("spdx_data.go", src, 0o644)
}

// fetchIDs pulls the SPDX JSON and returns lower(id)→canonical id. Deprecated
// ids are INCLUDED: a deprecated id (e.g. GPL-2.0) is still a valid SPDX
// expression and widely used in the wild, so the validator must accept it.
func fetchIDs(url, arrayKey, idKey string) (map[string]string, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	var doc map[string]json.RawMessage
	if err := json.NewDecoder(resp.Body).Decode(&doc); err != nil {
		return nil, err
	}
	var entries []map[string]any
	if err := json.Unmarshal(doc[arrayKey], &entries); err != nil {
		return nil, err
	}
	out := make(map[string]string, len(entries))
	for _, e := range entries {
		id, _ := e[idKey].(string)
		if id == "" {
			continue
		}
		out[strings.ToLower(id)] = id
	}
	return out, nil
}

func writeMap(b *strings.Builder, name string, m map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(b, "var %s = map[string]string{\n", name)
	for _, k := range keys {
		fmt.Fprintf(b, "\t%q: %q,\n", k, m[k])
	}
	b.WriteString("}\n")
}
